/* =========================================================
 * MOS Vocabulary Cards - 単語データ
 *
 * category: "common" (Word/Excel共通) | "excel" | "word"
 * jp      : 日本語の用語
 * reading : 読み方（ひらがな）。漢字が含まれる場合のみ画面にふりがなとして表示される
 * en      : 英語訳
 * desc    : やさしい日本語での説明
 * ========================================================= */

var VOCAB_WORDS = [

  /* ================= 共通操作 (common) ================= */
  { id: "COM-1",  category: "common", jp: "リボン", reading: "りぼん", en: "Ribbon",
    desc: "画面上部にある、ボタンやコマンドが並んだ帯。タブで表示内容が切り替わる。" },
  { id: "COM-2",  category: "common", jp: "タブ", reading: "たぶ", en: "Tab",
    desc: "リボンの上に並ぶ「ホーム」「挿入」などの見出し。クリックすると表示されるボタンが変わる。" },
  { id: "COM-3",  category: "common", jp: "クイックアクセスツールバー", reading: "くいっくあくせすつーるばー", en: "Quick Access Toolbar",
    desc: "画面の一番上にある、よく使うボタン（上書き保存など）を並べた小さいバー。" },
  { id: "COM-4",  category: "common", jp: "ファイルタブ", reading: "ふぁいるたぶ", en: "File tab",
    desc: "保存・開く・印刷などをまとめて行う画面（バックステージビュー）を開くタブ。" },
  { id: "COM-5",  category: "common", jp: "上書き保存", reading: "うわがきほぞん", en: "Save",
    desc: "今の内容を、同じファイル名のまま保存すること。" },
  { id: "COM-6",  category: "common", jp: "名前を付けて保存", reading: "なまえをつけてほぞん", en: "Save As",
    desc: "新しい名前や別のファイル形式で保存すること。" },
  { id: "COM-7",  category: "common", jp: "元に戻す", reading: "もとにもどす", en: "Undo",
    desc: "直前に行った操作を取り消すこと。" },
  { id: "COM-8",  category: "common", jp: "やり直し", reading: "やりなおし", en: "Redo",
    desc: "元に戻した操作を、もう一度やり直すこと。" },
  { id: "COM-9",  category: "common", jp: "コピー", reading: "こぴー", en: "Copy",
    desc: "選択した内容を、そのまま複製すること。" },
  { id: "COM-10", category: "common", jp: "切り取り", reading: "きりとり", en: "Cut",
    desc: "選択した内容を削除して、貼り付け用に一時保存すること。" },
  { id: "COM-11", category: "common", jp: "貼り付け", reading: "はりつけ", en: "Paste",
    desc: "コピーまたは切り取った内容を、別の場所に挿入すること。" },
  { id: "COM-12", category: "common", jp: "形式を選択して貼り付け", reading: "けいしきをせんたくしてはりつけ", en: "Paste Special",
    desc: "書式を含めるかどうかなど、貼り付け方を選べる機能。" },
  { id: "COM-13", category: "common", jp: "印刷プレビュー", reading: "いんさつぷれびゅー", en: "Print Preview",
    desc: "実際に印刷される見た目を、印刷する前に確認する画面。" },
  { id: "COM-14", category: "common", jp: "ページ設定", reading: "ぺーじせってい", en: "Page Setup",
    desc: "用紙のサイズ・向き・余白などを設定する機能。" },
  { id: "COM-15", category: "common", jp: "ズーム", reading: "ずーむ", en: "Zoom",
    desc: "画面の表示を拡大したり縮小したりすること。" },
  { id: "COM-16", category: "common", jp: "検索", reading: "けんさく", en: "Find",
    desc: "文書やシートの中から、指定した文字列を探す機能。" },
  { id: "COM-17", category: "common", jp: "置換", reading: "ちかん", en: "Replace",
    desc: "見つけた文字列を、別の文字列に置き換える機能。" },
  { id: "COM-18", category: "common", jp: "スペルチェック", reading: "すぺるちぇっく", en: "Spelling",
    desc: "入力ミスや誤字がないかを自動でチェックする機能。" },
  { id: "COM-19", category: "common", jp: "テーマ", reading: "てーま", en: "Theme",
    desc: "色・フォント・デザインをまとめて切り替える設定。" },
  { id: "COM-20", category: "common", jp: "PDF形式で保存", reading: "ぴーでぃーえふけいしきでほぞん", en: "Save/Export as PDF",
    desc: "作成したファイルを、PDFファイルとして保存すること。" },
  { id: "COM-21", category: "common", jp: "共有", reading: "きょうゆう", en: "Share",
    desc: "ファイルを他の人と一緒に見たり、編集したりできるようにすること。" },
  { id: "COM-22", category: "common", jp: "コメント", reading: "こめんと", en: "Comment",
    desc: "文書やセルに付けられるメモ。本文そのものは変わらない。" },
  { id: "COM-23", category: "common", jp: "校閲", reading: "こうえつ", en: "Review",
    desc: "文書の間違いを確認したり、修正の提案をしたりする作業（タブの名前でもある）。" },
  { id: "COM-24", category: "common", jp: "変更履歴の記録", reading: "へんこうりれきのきろく", en: "Track Changes",
    desc: "誰が・いつ・どこを修正したかを、自動で記録する機能。" },
  { id: "COM-25", category: "common", jp: "ショートカットキー", reading: "しょーとかっときー", en: "Shortcut key",
    desc: "キーボードの組み合わせだけで操作できる方法（例：Ctrl+C）。" },
  { id: "COM-26", category: "common", jp: "ステータスバー", reading: "すてーたすばー", en: "Status bar",
    desc: "画面の一番下にある、現在の状態（ページ数など）を表示する部分。" },
  { id: "COM-27", category: "common", jp: "オートコレクト", reading: "おーとこれくと", en: "AutoCorrect",
    desc: "よくある入力ミスを、自動的に正しい形へ修正する機能。" },
  { id: "COM-28", category: "common", jp: "互換性チェック", reading: "ごかんせいちぇっく", en: "Compatibility Checker",
    desc: "古いバージョンのソフトで開いたときに、問題が起きないか確認する機能。" },
  { id: "COM-29", category: "common", jp: "アクセシビリティチェック", reading: "あくせしびりてぃちぇっく", en: "Accessibility Checker",
    desc: "目や耳が不自由な人にも内容が伝わりやすいかを確認する機能。" },
  { id: "COM-30", category: "common", jp: "左揃え", reading: "ひだりぞろえ", en: "Align Left",
    desc: "文字を行の左端にそろえて配置すること。" },
  { id: "COM-31", category: "common", jp: "中央揃え", reading: "ちゅうおうぞろえ", en: "Center",
    desc: "文字を行の中央にそろえて配置すること。" },
  { id: "COM-32", category: "common", jp: "右揃え", reading: "みぎぞろえ", en: "Align Right",
    desc: "文字を行の右端にそろえて配置すること。" },
  { id: "COM-33", category: "common", jp: "両端揃え", reading: "りょうたんぞろえ", en: "Justify",
    desc: "行の左右どちらの端もそろうように、文字の間隔を自動で調整すること。" },
  { id: "COM-34", category: "common", jp: "太字", reading: "ふとじ", en: "Bold",
    desc: "文字を太く表示する書式。" },
  { id: "COM-35", category: "common", jp: "斜体", reading: "しゃたい", en: "Italic",
    desc: "文字を斜めに傾けて表示する書式。" },
  { id: "COM-36", category: "common", jp: "下線", reading: "かせん", en: "Underline",
    desc: "文字の下に線を引く書式。" },

  /* ================= Excel専用 ================= */
  { id: "XL-1",  category: "excel", jp: "セル", reading: "せる", en: "Cell",
    desc: "行と列が交わってできる、1つ1つのマス目。" },
  { id: "XL-2",  category: "excel", jp: "行", reading: "ぎょう", en: "Row",
    desc: "横方向に並ぶマスの集まり。左側に数字で番号が付く。" },
  { id: "XL-3",  category: "excel", jp: "列", reading: "れつ", en: "Column",
    desc: "縦方向に並ぶマスの集まり。上側にアルファベットで番号が付く。" },
  { id: "XL-4",  category: "excel", jp: "シート", reading: "しーと", en: "Sheet",
    desc: "1枚の作業用紙。1つのブックの中に複数作ることができる。" },
  { id: "XL-5",  category: "excel", jp: "ブック", reading: "ぶっく", en: "Workbook",
    desc: "Excelのファイル全体のこと。複数のシートをまとめたもの。" },
  { id: "XL-6",  category: "excel", jp: "セル番地", reading: "せるばんち", en: "Cell reference",
    desc: "「B3」のように、列のアルファベットと行の数字で表すセルの位置。" },
  { id: "XL-7",  category: "excel", jp: "相対参照", reading: "そうたいさんしょう", en: "Relative reference",
    desc: "コピーした先に合わせて、参照先が自動でずれる参照方法。" },
  { id: "XL-8",  category: "excel", jp: "絶対参照", reading: "ぜったいさんしょう", en: "Absolute reference",
    desc: "$を付けることで、コピーしても参照先が変わらないようにする方法。" },
  { id: "XL-9",  category: "excel", jp: "複合参照", reading: "ふくごうさんしょう", en: "Mixed reference",
    desc: "行または列のどちらか片方だけを$で固定する参照方法。" },
  { id: "XL-10", category: "excel", jp: "数式", reading: "すうしき", en: "Formula",
    desc: "「=」から始まる、計算を行うための式。" },
  { id: "XL-11", category: "excel", jp: "関数", reading: "かんすう", en: "Function",
    desc: "SUMやIFのように、あらかじめ用意された計算方法。" },
  { id: "XL-12", category: "excel", jp: "引数", reading: "ひきすう", en: "Argument",
    desc: "関数を使うときに、（　）の中に入れる値や条件のこと。" },
  { id: "XL-13", category: "excel", jp: "オートフィル", reading: "おーとふぃる", en: "AutoFill",
    desc: "フィルハンドルをドラッグして、連続データや数式を自動で入力する機能。" },
  { id: "XL-14", category: "excel", jp: "フィルハンドル", reading: "ふぃるはんどる", en: "Fill handle",
    desc: "セルの右下にある小さい四角。ドラッグするとオートフィルができる。" },
  { id: "XL-15", category: "excel", jp: "条件付き書式", reading: "じょうけんつきしょしき", en: "Conditional Formatting",
    desc: "設定した条件に当てはまるセルだけ、色や文字を変える機能。" },
  { id: "XL-16", category: "excel", jp: "並べ替え", reading: "ならべかえ", en: "Sort",
    desc: "データを大きい順・小さい順・五十音順などに整理すること。" },
  { id: "XL-17", category: "excel", jp: "フィルター", reading: "ふぃるたー", en: "Filter",
    desc: "条件に合うデータだけを画面に表示する機能。" },
  { id: "XL-18", category: "excel", jp: "ピボットテーブル", reading: "ぴぼっとてーぶる", en: "PivotTable",
    desc: "大量のデータを、項目ごとに集計・分析するための表。" },
  { id: "XL-19", category: "excel", jp: "グラフ", reading: "ぐらふ", en: "Chart",
    desc: "数値データを、図で分かりやすく表したもの。" },
  { id: "XL-20", category: "excel", jp: "スパークライン", reading: "すぱーくらいん", en: "Sparkline",
    desc: "1つのセルの中に表示できる、小さなミニグラフ。" },
  { id: "XL-21", category: "excel", jp: "名前の定義", reading: "なまえのていぎ", en: "Named Range",
    desc: "セルの範囲に名前を付けて、数式の中で使えるようにする機能。" },
  { id: "XL-22", category: "excel", jp: "テーブル", reading: "てーぶる", en: "Table",
    desc: "データの範囲を、管理しやすい表の形式に変える機能。" },
  { id: "XL-23", category: "excel", jp: "入力規則", reading: "にゅうりょくきそく", en: "Data Validation",
    desc: "セルに入力できる値の種類やリストを制限する機能。" },
  { id: "XL-24", category: "excel", jp: "ウィンドウ枠の固定", reading: "うぃんどうわくのこてい", en: "Freeze Panes",
    desc: "スクロールしても、見出しの行や列を画面に固定して表示し続ける機能。" },
  { id: "XL-25", category: "excel", jp: "シートの保護", reading: "しーとのほご", en: "Protect Sheet",
    desc: "他の人がセルの内容を編集できないようにする機能。" },
  { id: "XL-26", category: "excel", jp: "セルを結合して中央揃え", reading: "せるをけつごうしてちゅうおうぞろえ", en: "Merge & Center",
    desc: "複数のセルを1つにまとめ、文字をその中央に表示する機能。" },
  { id: "XL-27", category: "excel", jp: "表示形式", reading: "ひょうじけいしき", en: "Number Format",
    desc: "数値を通貨・日付・パーセントなどの見た目に変える設定。" },
  { id: "XL-28", category: "excel", jp: "罫線", reading: "けいせん", en: "Border",
    desc: "セルの周りに引く線のこと。" },
  { id: "XL-29", category: "excel", jp: "塗りつぶしの色", reading: "ぬりつぶしのいろ", en: "Fill Color",
    desc: "セルの背景に色をつけること。" },
  { id: "XL-30", category: "excel", jp: "桁区切りスタイル", reading: "けたくぎりすたいる", en: "Comma Style",
    desc: "数値を3桁ごとにカンマ（,）で区切って表示する形式。" },
  { id: "XL-31", category: "excel", jp: "折れ線グラフ", reading: "おれせんぐらふ", en: "Line chart",
    desc: "時間による数値の変化を、線のつながりで表すグラフ。" },
  { id: "XL-32", category: "excel", jp: "円グラフ", reading: "えんぐらふ", en: "Pie chart",
    desc: "全体に対する割合を、円の扇形で表すグラフ。" },
  { id: "XL-33", category: "excel", jp: "棒グラフ", reading: "ぼうぐらふ", en: "Bar/Column chart",
    desc: "数値の大きさを、棒の長さで比べるグラフ。" },
  { id: "XL-34", category: "excel", jp: "SUM関数", reading: "さむかんすう", en: "SUM function",
    desc: "指定した範囲の数値の合計を求める関数。" },
  { id: "XL-35", category: "excel", jp: "AVERAGE関数", reading: "あべれーじかんすう", en: "AVERAGE function",
    desc: "指定した範囲の数値の平均を求める関数。" },
  { id: "XL-36", category: "excel", jp: "IF関数", reading: "いふかんすう", en: "IF function",
    desc: "条件が正しいかどうかで、返す答えを変える関数。" },
  { id: "XL-37", category: "excel", jp: "COUNTIF関数", reading: "かうんといふかんすう", en: "COUNTIF function",
    desc: "指定した条件に合うセルの数を数える関数。" },
  { id: "XL-38", category: "excel", jp: "VLOOKUP関数", reading: "ぶいるっくあっぷかんすう", en: "VLOOKUP function",
    desc: "表を縦方向に検索して、対応する値を取り出す関数。" },
  { id: "XL-39", category: "excel", jp: "循環参照", reading: "じゅんかんさんしょう", en: "Circular reference",
    desc: "数式が自分自身のセルを参照してしまい、計算できなくなるエラー。" },
  { id: "XL-40", category: "excel", jp: "エラー値", reading: "えらーち", en: "Error value",
    desc: "「#DIV/0!」のように、計算できないときにセルに表示される印。" },
  { id: "XL-41", category: "excel", jp: "ワークシートのグループ化", reading: "わーくしーとのぐるーぷか", en: "Group worksheets",
    desc: "複数のシートをまとめて選択し、同じ操作を一度に行う機能。" },
  { id: "XL-42", category: "excel", jp: "行の高さ", reading: "ぎょうのたかさ", en: "Row height",
    desc: "行の縦方向の大きさ。" },
  { id: "XL-43", category: "excel", jp: "列の幅", reading: "れつのはば", en: "Column width",
    desc: "列の横方向の大きさ。" },
  { id: "XL-44", category: "excel", jp: "セルの結合", reading: "せるのけつごう", en: "Merge Cells",
    desc: "複数のセルを1つのセルにまとめること。" },
  { id: "XL-45", category: "excel", jp: "改ページプレビュー", reading: "かいぺーじぷれびゅー", en: "Page Break Preview",
    desc: "印刷されるページの区切り位置を確認・調整できる画面。" },
  { id: "XL-46", category: "excel", jp: "印刷範囲", reading: "いんさつはんい", en: "Print Area",
    desc: "印刷したいセルの範囲だけを指定する設定。" },
  { id: "XL-47", category: "excel", jp: "ヘッダーとフッター", reading: "へっだーとふった―", en: "Header and Footer",
    desc: "全ページの上下に共通して表示する文字（日付・ページ番号など）。" },
  { id: "XL-48", category: "excel", jp: "ドロップダウンリスト", reading: "どろっぷだうんりすと", en: "Drop-down list",
    desc: "クリックすると選択肢が表示され、その中から選んで入力できる仕組み。" },
  { id: "XL-49", category: "excel", jp: "数式バー", reading: "すうしきばー", en: "Formula bar",
    desc: "選択したセルに入っている数式や文字を表示・編集する部分。" },
  { id: "XL-50", category: "excel", jp: "名前ボックス", reading: "なまえぼっくす", en: "Name Box",
    desc: "今選択しているセルの番地や、付けた名前を表示する部分。" },
  { id: "XL-51", category: "excel", jp: "ゴールシーク", reading: "ごーるしーく", en: "Goal Seek",
    desc: "求めたい結果から逆算して、必要な入力値を計算する機能。" },
  { id: "XL-52", category: "excel", jp: "スライサー", reading: "すらいさー", en: "Slicer",
    desc: "テーブルやピボットテーブルを、ボタンをクリックするだけで絞り込める機能。" },
  { id: "XL-53", category: "excel", jp: "ふりがなの表示", reading: "ふりがなのひょうじ", en: "Show Furigana",
    desc: "漢字の読み方を、セルの文字の上に表示する機能。" },

  /* ================= Word専用 ================= */
  { id: "WD-1",  category: "word", jp: "段落", reading: "だんらく", en: "Paragraph",
    desc: "文章のひとまとまり。Enterキーで改行すると新しい段落になる。" },
  { id: "WD-2",  category: "word", jp: "インデント", reading: "いんでんと", en: "Indent",
    desc: "段落の左右の開始位置を、内側にずらすこと。" },
  { id: "WD-3",  category: "word", jp: "行間", reading: "ぎょうかん", en: "Line spacing",
    desc: "行と行のあいだの、上下の広さ。" },
  { id: "WD-4",  category: "word", jp: "文字間隔", reading: "もじかんかく", en: "Character spacing",
    desc: "文字と文字のあいだの、横の広さ。" },
  { id: "WD-5",  category: "word", jp: "フォント", reading: "ふぉんと", en: "Font",
    desc: "文字の形（書体）のこと。" },
  { id: "WD-6",  category: "word", jp: "フォントサイズ", reading: "ふぉんとさいず", en: "Font size",
    desc: "文字の大きさ。" },
  { id: "WD-7",  category: "word", jp: "スタイル", reading: "すたいる", en: "Style",
    desc: "フォント・色・行間などの書式を、まとめて1つの名前で登録したもの。" },
  { id: "WD-8",  category: "word", jp: "見出し", reading: "みだし", en: "Heading",
    desc: "章やセクションのタイトルに使う、専用のスタイル。" },
  { id: "WD-9",  category: "word", jp: "目次", reading: "もくじ", en: "Table of Contents",
    desc: "文書内の見出しを自動で集めて作られる一覧。" },
  { id: "WD-10", category: "word", jp: "ヘッダー", reading: "へっだー", en: "Header",
    desc: "各ページの上部に、共通で表示される部分。" },
  { id: "WD-11", category: "word", jp: "フッター", reading: "ふった―", en: "Footer",
    desc: "各ページの下部に、共通で表示される部分。" },
  { id: "WD-12", category: "word", jp: "ページ番号", reading: "ぺーじばんごう", en: "Page number",
    desc: "各ページに自動で表示される番号。" },
  { id: "WD-13", category: "word", jp: "セクション区切り", reading: "せくしょんくぎり", en: "Section break",
    desc: "1つの文書の中で、ページ設定を部分的に変えるための区切り。" },
  { id: "WD-14", category: "word", jp: "差し込み印刷", reading: "さしこみいんさつ", en: "Mail Merge",
    desc: "名簿などのデータを使って、宛先ごとに内容が変わる文書を一度に作る機能。" },
  { id: "WD-15", category: "word", jp: "宛先の選択", reading: "あてさきのせんたく", en: "Select Recipients",
    desc: "差し込み印刷で使う、宛先データの一覧を選ぶこと。" },
  { id: "WD-16", category: "word", jp: "図形", reading: "ずけい", en: "Shape",
    desc: "四角形・丸・矢印などを描くための図形オブジェクト。" },
  { id: "WD-17", category: "word", jp: "ワードアート", reading: "わーどあーと", en: "WordArt",
    desc: "色や形を装飾した、特殊な見た目の文字。" },
  { id: "WD-18", category: "word", jp: "SmartArt", reading: "すまーとあーと", en: "SmartArt",
    desc: "組織図や手順図などの図解を、簡単に作れる機能。" },
  { id: "WD-19", category: "word", jp: "表", reading: "ひょう", en: "Table",
    desc: "行と列を使って、データを整理して表示する枠組み。" },
  { id: "WD-20", category: "word", jp: "セルの結合", reading: "せるのけつごう", en: "Merge Cells",
    desc: "表の中の複数のセルを、1つのセルにまとめること。" },
  { id: "WD-21", category: "word", jp: "脚注", reading: "きゃくちゅう", en: "Footnote",
    desc: "ページの下部に表示する、補足の説明。" },
  { id: "WD-22", category: "word", jp: "相互参照", reading: "そうごさんしょう", en: "Cross-reference",
    desc: "図表番号やページ番号などを、自動でリンクさせる機能。" },
  { id: "WD-23", category: "word", jp: "ハイパーリンク", reading: "はいぱーりんく", en: "Hyperlink",
    desc: "クリックすると、別の場所やWebサイトへ移動できるリンク。" },
  { id: "WD-24", category: "word", jp: "変更履歴の記録", reading: "へんこうりれきのきろく", en: "Track Changes",
    desc: "誰が・どこを修正したかを記録し、あとで確認できるようにする機能。" },
  { id: "WD-25", category: "word", jp: "透かし", reading: "すかし", en: "Watermark",
    desc: "ページの背景に、うっすらと表示する文字や画像。" },
  { id: "WD-26", category: "word", jp: "テンプレート", reading: "てんぷれーと", en: "Template",
    desc: "あらかじめデザインが作られている、文書のひな形。" },
  { id: "WD-27", category: "word", jp: "段組み", reading: "だんぐみ", en: "Columns",
    desc: "1ページの中を、新聞のように複数の段（カラム）に分ける機能。" },
  { id: "WD-28", category: "word", jp: "タブとリーダー", reading: "たぶとりーだー", en: "Tabs and Leaders",
    desc: "タブキーで移動する位置と、その間を埋める点線などをまとめて設定する機能。" },
  { id: "WD-29", category: "word", jp: "箇条書き", reading: "かじょうがき", en: "Bullets",
    desc: "記号（・など）を付けて、項目を並べて書く書き方。" },
  { id: "WD-30", category: "word", jp: "段落番号", reading: "だんらくばんごう", en: "Numbering",
    desc: "数字を自動で付けながら、項目を並べて書く書き方。" },
  { id: "WD-31", category: "word", jp: "均等割り付け", reading: "きんとうわりつけ", en: "Distributed alignment",
    desc: "文字を、指定した幅いっぱいに均等な間隔で配置すること。" },
  { id: "WD-32", category: "word", jp: "ドロップキャップ", reading: "どろっぷきゃっぷ", en: "Drop Cap",
    desc: "段落のいちばん最初の文字だけを大きくして目立たせる装飾。" },
  { id: "WD-33", category: "word", jp: "改ページ", reading: "かいぺーじ", en: "Page Break",
    desc: "そこで強制的に文章を区切り、続きを次のページへ移す機能。" },
  { id: "WD-34", category: "word", jp: "改行", reading: "かいぎょう", en: "Line Break",
    desc: "段落は変えずに、文字だけを次の行に移すこと（Shift+Enterで入力）。" },
  { id: "WD-35", category: "word", jp: "書式のコピー/貼り付け", reading: "しょしきのこぴー・はりつけ", en: "Format Painter",
    desc: "選択した文字の書式だけをコピーして、別の場所に適用する機能。" },
  { id: "WD-36", category: "word", jp: "ナビゲーションウィンドウ", reading: "なびげーしょんうぃんどう", en: "Navigation Pane",
    desc: "見出しの一覧や検索結果から、文書内をすばやく移動できる画面。" },
  { id: "WD-37", category: "word", jp: "スタイルセット", reading: "すたいるせっと", en: "Style Set",
    desc: "文書全体の見た目のデザインを、まとめて切り替える機能。" },
  { id: "WD-38", category: "word", jp: "索引", reading: "さくいん", en: "Index",
    desc: "用語とページ番号を対応させて、巻末にまとめた一覧。" },
  { id: "WD-39", category: "word", jp: "図表番号", reading: "ずひょうばんごう", en: "Caption",
    desc: "図や表に付ける、説明文と通し番号。" },
  { id: "WD-40", category: "word", jp: "文書の保護", reading: "ぶんしょのほご", en: "Protect Document",
    desc: "他の人が文書を編集できないように、制限をかける機能。" },
  { id: "WD-41", category: "word", jp: "校正言語", reading: "こうせいげんご", en: "Proofing Language",
    desc: "スペルチェックなどで使う、文章の言語の設定。" },
  { id: "WD-42", category: "word", jp: "ドキュメント検査", reading: "どきゅめんとけんさ", en: "Document Inspector",
    desc: "個人情報やコメントなど、見えない情報が残っていないか確認する機能。" },
  { id: "WD-43", category: "word", jp: "既定のフォント", reading: "きていのふぉんと", en: "Default font",
    desc: "新しい文書を作ったときに、最初から使われているフォントの設定。" },
];
